// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2GPRFZ1RLUMKjt2nQY83-QoedFmeaCg',
    appId: '1:228099776960:web:d50ebf6e597ed425abe825',
    messagingSenderId: '228099776960',
    projectId: 'coden-2e07a',
    authDomain: 'coden-2e07a.firebaseapp.com',
    storageBucket: 'coden-2e07a.firebasestorage.app',
    measurementId: 'G-4TT8RKGYHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEYwpMs4Xcs1jkB8L_UbsG8Hgfg5LjD0',
    appId: '1:228099776960:android:e04086863f7b955eabe825',
    messagingSenderId: '228099776960',
    projectId: 'coden-2e07a',
    storageBucket: 'coden-2e07a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Sh-EQZhxDYm0oROWfLxjySmTkWLEk7Q',
    appId: '1:228099776960:ios:c0847e67063cfba9abe825',
    messagingSenderId: '228099776960',
    projectId: 'coden-2e07a',
    storageBucket: 'coden-2e07a.firebasestorage.app',
    iosClientId: '228099776960-ue6on8dmea562p3a0smvt3qjitui9kqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.codelearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Sh-EQZhxDYm0oROWfLxjySmTkWLEk7Q',
    appId: '1:228099776960:ios:c0847e67063cfba9abe825',
    messagingSenderId: '228099776960',
    projectId: 'coden-2e07a',
    storageBucket: 'coden-2e07a.firebasestorage.app',
    iosClientId: '228099776960-ue6on8dmea562p3a0smvt3qjitui9kqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.codelearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2GPRFZ1RLUMKjt2nQY83-QoedFmeaCg',
    appId: '1:228099776960:web:69625b4d371bc7aeabe825',
    messagingSenderId: '228099776960',
    projectId: 'coden-2e07a',
    authDomain: 'coden-2e07a.firebaseapp.com',
    storageBucket: 'coden-2e07a.firebasestorage.app',
    measurementId: 'G-4VZDBNK321',
  );
}
